RUB-27: add React, add basic Template
sonishc/Ruby_Combats pull request #27
Opened 2017-10-08 10:24 UTC by vlodkopits

# REVIEWERS

- [ ] @UAVova 
- [ ] @mayar2610 

# DESCRIPTION

**Add React(react-rails), add gem react-rails-img to render img, add basic Tamplate and Styles.**

# TEST COVERAGE

**no test.**

# EXPERT REVIEW

- [ ] @rokor
- [ ] @okohuch

2017-10-08 12:13 UTC, okohuch commented on app/assets/stylesheets/main.scss
> +			color: $burgundy;
Change tab to 2 spaces and fix alignment in this file.

2017-10-08 12:13 UTC, okohuch commented on app/views/layouts/application.html.erb
> +  	<%= react_component("Navbar") %>
alignment should be 2 spaces

2017-10-08 13:20 UTC, mayar2610 approved these changes

2017-10-08 14:53 UTC, intsrc approved these changes

2017-10-09 08:01 UTC, rokor requested changes

2017-10-09 08:01 UTC, rokor commented on app/assets/javascripts/components/navbar.jsx
> +                <span className="icon-bar"></span>
duplication happening with span.

2017-10-09 08:01 UTC, rokor commented on app/assets/javascripts/components/navbar.jsx
> +                <li><a href={ this.state.urlSignin } >Sign In</a></li>
up to line 41 should be dynamically generated.

2017-10-09 08:01 UTC, rokor commented on app/assets/javascripts/components/navbar.jsx
> +      urlRoot: "/",
should be moved to const in separate folder and file

2017-10-09 08:01 UTC, rokor commented on app/assets/javascripts/components/footer.jsx
> +
empty state not the best idea.

2017-10-10 11:44 UTC, rokor commented on app/assets/javascripts/components/navbar.jsx
> +      return <Tag key={index} className={name}></Tag>;
() should follow after return when we generate elements. For example `return (<Tag key={index} className={name}></Tag>);`

2017-10-10 11:44 UTC, rokor commented on app/assets/javascripts/components/navbar.jsx
> +      return  <li key={index}>
same issue as above

2017-10-10 18:26 UTC, rokor approved these changes

2017-10-10 23:16 UTC, merged